EPOCH = 40
SHOW_AUX_POS = 0

DEVICE = 'mps'

TRAIN_MODEL_MORE = 1
STARTING_EPOCH = 20
EPOCHS_TO_TRAIN = 20

LEARNING_RATE = 0.0001
BATCH_SIZE = 128
USE_LSTM = 1

GATHER_DATA = False

IMAGE_SIZE = 128
NO_SAMPLES = 50000

FPS = 240.
TIME_STEP = 1. / FPS

CAMERA_DISTANCE = 1.1
CAMERA_YAW = 0
CAMERA_PITCH = -30
CAMERA_TARGET_POSITION = [0, 0, 0]

MAX_CUBE_RANDOM = 0.1
MAX_START_RANDOM_XZ = 0.01
MAX_START_RANDOM_Y = 0.2

GRIPPER_OPEN = 0.04
GRIPPER_CLOSE = 0.0

PANDA_END_EFFECTOR_INDEX = 11
PANDA_DOFS = 7

LL = [-7] * PANDA_DOFS
UL = [7] * PANDA_DOFS
JR = [7] * PANDA_DOFS

STARTING_JOINT_POSITIONS = [1.599, -0.390, -0.019, -3.042, -0.015, 2.651, 0.8, 0.02, 0.02]
RP = STARTING_JOINT_POSITIONS

# TODO ADD LSTM VARIABLE TO PATH
MODEL_PATH = 'models/model-' + str(IMAGE_SIZE) + 'px-' + str(int(NO_SAMPLES / 1000)) + 'k' + ('-lstm' if USE_LSTM else '')
IMAGES_PATH = 'images_cube_table/image_'
EPOCH_LOSSES_PATH = MODEL_PATH + '_epoch_losses'