EPOCH = 20
SHOW_AUX_POS = 0

DEVICE = 'mps'

TRAIN_MODEL_MORE = 1
STARTING_EPOCH = 2
EPOCHS_TO_TRAIN = 18

LEARNING_RATE = 0.0001
BATCH_SIZE = 128
USE_LSTM = 1

GATHER_DATA = True
GATHER_DATA_MORE = 0
STARTING_SAMPLES = 0

IMAGE_SIZE = 128
NO_SAMPLES = 200000

FPS = 240.
TIME_STEP = 1. / FPS
WAIT_TIME_DROP = 0.2
WAIT_TIME_OTHER = 0.1
REACHED_TARGET_THRESHOLD = 0.01
ROBOT_SPEED = 0.1

CAMERA_DISTANCE = 1.1
CAMERA_YAW = 0
CAMERA_PITCH = -30
CAMERA_TARGET_POSITION = [0, 0, 0]

MAX_CUBE_RANDOM = 0.15
MAX_START_RANDOM_XZ = 0.03
MAX_START_RANDOM_Y = 0.05

GRIPPER_OPEN = 0.04
GRIPPER_CLOSE = 0.0

PANDA_END_EFFECTOR_INDEX = 11
PANDA_DOFS = 7

LL = [-7] * PANDA_DOFS
UL = [7] * PANDA_DOFS
JR = [7] * PANDA_DOFS

STARTING_JOINT_POSITIONS = [1.512, -0.228, 0.065, -2.875, 0.030, 2.647, 0.8, 0.02, 0.02]
RP = STARTING_JOINT_POSITIONS

MODEL_PATH = 'models/model-' + str(IMAGE_SIZE) + 'px-' + str(int(NO_SAMPLES / 1000)) + 'k' + ('-lstm' if USE_LSTM else '')
IMAGES_PATH = 'images_cube_table/image_'
EPOCH_LOSSES_PATH = MODEL_PATH + '_epoch_losses'
SAMPLE_LABEL_PATH = 'labels/sample_labels-' + str(IMAGE_SIZE) + 'px-' + str(int(NO_SAMPLES / 1000)) + 'k'

#TO DO add sample_labels PATH

NO_CAMERAS = 3

CAMERA_POSITIONS = {
    "camera_1": {
        "distance": 0,
        "yaw": 0,
        "pitch": 0,
        "target_positon": 0,
    }
}